version: "3.2"

services:
  dev:
    container_name: smart-audit
    image: paritytech/ci-linux:production
    working_dir: /var/www/smart-audit
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/smart-audit/.cargo
    volumes:
      - .:/var/www/smart-audit
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/smart-audit --dev --ws-external"
